config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about", to: "pages#about"
  resources :dogs
  get "signup", to: "owners#new"
  resources :owners, except: [:new]
  resources :members, only: [:index]
  resources :herdings
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :sports
end

app/models/owner.rb
class Owner < ApplicationRecord
        belongs_to :member
        has_many :dogs
        before_validation { self.email = email.downcase}

        validate :compulsory_fields
        has_secure_password

        private

        def compulsory_fields
                errors.add(:base, "Musíte zadat křestní jméno") if first_name.blank?
                errors.add(:base, "Musíte zadat příjmení") if last_name.blank?
                errors.add(:base, "Musíte zadat email") if email.blank?
                errors.add(:base, "Nesprávný formát emailu") unless email =~ /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
        end

end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController

    def show
        @owner = Owner.find(params[:id])
    end
    
    def new
        @owner = Owner.new
    end

    def create
        debugger
        @owner = Owner.new(params.require(:owner).permit(:first_name, :last_name, :email, :password))
        member = Member.find_by(first_name: params[:owner][:first_name], last_name: params[:owner][:last_name])
        if member.present? && !member.owner.present?
            @owner.member = member
        end
        if @owner.save
            session[:owner_id] = @owner.id
            flash[:notice] = "Člen #{@owner.first_name} #{@owner.last_name} byl úspěšně registrován"
            redirect_to owner_path(@owner)
        else
            render "new", status: 422
        end
    end

    def edit
        @owner = Owner.find(params[:id])
    end

    def update
        @owner = Owner.find(params[:id])
        if @owner.update(params.require(:owner).permit(:first_name, :last_name, :email, :password))
            flash[:notice] = "Váš účet byl úspěšně upraven"
            redirect_to members_path
        else
            render "edit"
        end
    end
end

app/views/owners/_others.html.erb
<div class="container text-center">
    <% dogs = Dog.where(owner_id: @owner.id) %>
    <% if dogs.present? && !dogs.empty? %>
        <h4>Psi člena <%= @owner.first_name%> <%= @owner.last_name %> </h4>
        <div class="container">
            <table class="table table-dark text-center">
                <thead>
                <tr>
                    <th scope="col">Jméno</th>
                    <th scope="col">Datum narození</th>
                    <th scope="col" colspan="1"></th>
                </tr>
                </thead>
                <tbody>
                    
                <%dogs.each do |dog| %>
                <tr>
                    <td><%= dog.dog_name %> </td>
                    <td><%= dog.date_of_birth.strftime("%d.%m.%Y") %></td>
                    <td>    
                        <%= link_to "Detaily", dog_path(dog), method: :get, class: "btn btn-success" %>
                    </td>
                </tr>
                <% end %>
                </tbody>
            </table>
        </div>
    <% end %>
    
    

app/views/owners/_owner.html.erb
<div class="container text-center">
    <% dogs = Dog.where(owner_id: @owner.id) %>
    <% if dogs.present? && !dogs.empty? %>
        <h4>Vaši psi</h4>
        <div class="container">
            <table class="table table-dark text-center">
                <thead>
                <tr>
                    <th scope="col">Jméno</th>
                    <th scope="col">Datum narození</th>
                    <th scope="col" colspan="2"></th>
                </tr>
                </thead>
                <tbody>
                    
                <%dogs.each do |dog| %>
                <tr>
                    <td><%= dog.dog_name %> </td>
                    <td><%= dog.date_of_birth.strftime("%d.%m.%Y") %></td>
                    <td>
                        <%= link_to "Upravit údaje psa", edit_dog_path(dog), method: :get, class: "btn btn-success" %>    
                        <%= link_to "Detaily", dog_path(dog), method: :get, class: "btn btn-success" %>
                        <%= link_to "Vymazat psa", dog_path(dog), method: :delete, class: "btn btn-danger delete-link", data: { turbo_method: :delete, "turbo-confirm": "Are you sure?" } %>
                    </td>
                </tr>
                <% end %>
                </tbody>
            </table>
        </div>
    <% end %>
    
    <%= link_to "Změnit přihlašovací údaje", edit_owner_path(@owner), class: "btn btn-success" %>
    <%= link_to "Přidat nového psa", new_dog_path, class: "btn btn-success" %>
    
</div>
    
    

app/views/owners/edit.html.erb
<%= render partial: "shared/error", locals: { obj: @owner } %>   

<h1 class="text-center">Změnit přihlašovací údaje</h1>

    <div class="container">
        <%= form_with(model: @owner, local: true) do |f| %>
          <div class="mb-3">
            <%= f.label :email, "Email", class: "form-label" %>
            <%= f.text_field :email, class: "form-control", placeholder: "Email"%>
          </div>
          <div class="mb-3">
            <%= f.label :password, "Nové heslo", class: "form-label" %>
            <%= f.password_field :password, class: "form-control"%>
          </div>
          <div class="mb-3">
            <%= f.submit "Změnit", class: "btn btn-warning" %>
          </div>
        <% end %>
        </div>
    
    <div class="container">
        <%= link_to "Zpět na Váš účet", owner_path(current_owner), class: "btn btn-success" %>
    </div> 
    
    
    
    
    
    
    
    
    
    
    
    
    

app/views/owners/new.html.erb
<div class="container">
<h4>Registrovat se mohou pouze členové KCHCS</h4>
<%= link_to "Seznam členů", members_path, method: :get, class: "btn btn-success" %>
</div>

<%= render partial: "shared/error", locals: { obj: @owner } %>    
 
<div class="container">
        <%= form_with(model: @owner, local: true) do |f| %>
          <div class="mb-3">
            <%= f.label :first_name, "Křestní jméno", class: "form-label" %>
            <%= f.text_field :first_name, class: "form-control", placeholder: "First name" , value: params[:first_name]%>
          </div>
          <div class="mb-3">
            <%= f.label :last_name, "Příjmení", class: "form-label" %>
            <%= f.text_field :last_name, class: "form-control", placeholder: "Last name", value: params[:last_name] %>
          </div>
          <div class="mb-3">
            <%= f.label :email,"Email", class: "form-label" %>
            <%= f.text_field :email, class: "form-control", placeholder: "Email", value: params[:email]%>
          </div>
          <div class="mb-3">
            <%= f.label :password,"Heslo", class: "form-label" %>
            <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
          </div>
          <div class="mb-3">
            <%= f.submit "Registrovat", class: "btn btn-warning" %>
          </div>
        <% end %>
</div>
    
    
    
    
    
    
    
    
    
    
    
    

app/views/owners/show.html.erb
<% if logged_in? && current_owner.id == @owner.id %>
    <%= render partial: "owner"%>
<% else %>
    <%= render partial: "others"%>
<% end %>