config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about", to: "pages#about"
  resources :dogs
  get "signup", to: "owners#new"
  resources :owners, except: [:new]
  resources :members, only: [:index]
  resources :herdings
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :sports
end

app/models/dog.rb
class Dog < ApplicationRecord
    belongs_to :owner    
    has_many :herdings, dependent: :destroy

    validate :compulsory_inputs

    private

    def compulsory_inputs
        if dog_name.blank?
            errors.add(:base, "Musíte zadat jméno psa")
        end
        if date_of_birth.blank?
            errors.add(:base, "Musíte zadat datum narození psa")
        end
    end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
    def index
        @dogs = Dog.all
    end

    def show
        @dog = Dog.find(params[:id])
    end

    def new
        @dog = Dog.new
    end

    def create 
        @dog = Dog.new(params.require(:dog).permit(:dog_name, :date_of_birth))
        @dog.owner = current_owner
        if @dog.save 
            flash[:notice] = "Údaje psa byly přidány"
            redirect_to owner_path(Owner.find(@dog.owner_id))
        else
            render "new", status: 422
        end
    end

    def edit
        @dog = Dog.find(params[:id])
    end

    def update
        @dog = Dog.find(params[:id])
        if @dog.update(params.require(:dog).permit(:dog_name, :date_of_birth))
            flash[:notice] = "Údaje psa byly úspěšně upraveny"
            redirect_to owner_path(Owner.find(@dog.owner_id))
        else
            render "edit", status: 422
        end
    end

    def destroy
        @dog = Dog.find(params[:id])
        @dog.destroy
        redirect_to owner_path(Owner.find(@dog.owner_id))
    end
end

app/views/dogs/_dog_owner.html.erb
<div class="container text-center">
    <h2>Stránka psa <%= @dog.dog_name%></h2>
    
    
</div>
<% results = Herding.where(dog_id: @dog.id) %>

<% if results.present? && !results.empty? %>
<div class="container">   
    <h3>Pasení</h3> 

    <div class="container">
        <table class="table table-dark text-center">
            <thead>
            <tr>
                <th scope="col">Kategorie</th>
                <th scope="col">Místo konání akce</th>
                <th scope="col">Datum konání akce</th>
                <th scope="col">Počet bodů</th>
                <th scope="col">Pořadí</th>
                <th scope="col">Počet soupeřů</th>
                <th scope="col">Body do SPR</th>
                <th scope="col" colspan="2"></th>
            </tr>
            </thead>
            <tbody>
                
            <%results.each do |r| %>
            <tr>
                <td><%= r.category %> </td>
                <td><%= r.event_place %> </td>
                <td><%= r.event_date.strftime("%d.%m.%Y") %> </td>
                <td><%= r.points %> </td>
                <td><%= r.position %> </td>
                <td><%= r.num_dogs %> </td>
                <td><%= r.final_points %></td>
                <td><%= link_to "Upravit výsledek", edit_herding_path(r), method: :get, class: "btn btn-success" %>
                    <%= link_to "Smazat výsledek", herding_path(r), method: :delete, class: "btn btn-danger delete-link", data: { turbo_method: :delete, confirm: "Are you sure?" } %>
                </td>
            </tr>
            <% end %>
            </tbody>
        </table>
    </div>
    
</div>
<% end %>
<div class="container">
    <%= link_to "Přídat nový výsledek", new_herding_path(dog_id: @dog.id), method: :get, class: "btn btn-success" %>
<%= link_to "Zpět na Váš účet", owner_path(@dog.owner_id), method: :get, class: "btn btn-success" %>
</div>

app/views/dogs/_other_owners.html.erb
<div class="container text-center">
    <h2>Stránka psa <%= @dog.dog_name%></h2>
    
</div>
<% results = Herding.where(dog_id: @dog.id) %>

<% if results.present? && !results.empty? %>
<div class="container">   
    <h3>Pasení</h3> 

    <div class="container">
        <table class="table table-dark text-center">
            <thead>
            <tr>
                <th scope="col">Kategorie</th>
                <th scope="col">Místo konání akce</th>
                <th scope="col">Datum konání akce</th>
                <th scope="col">Počet bodů</th>
                <th scope="col">Pořadí</th>
                <th scope="col">Počet soupeřů</th>
                <th scope="col">Počet získaných bodů</th>
            </tr>
            </thead>
            <tbody>
                
            <%results.each do |r| %>
            <tr>
                <td><%= r.category %> </td>
                <td><%= r.event_place %> </td>
                <td><%= r.event_date.strftime("%d.%m.%Y") %> </td>
                <td><%= r.points %> </td>
                <td><%= r.position %> </td>
                <td><%= r.num_dogs %> </td>
                <td><%= r.final_points %></td>
            </tr>
            <% end %>
            </tbody>
        </table>
    </div>
    
</div>
<% end %>
<div class="container">
<%= link_to "Informace o majiteli", owner_path(@dog.owner_id), method: :get, class: "btn btn-success" %>
</div>

app/views/dogs/edit.html.erb
<%= render partial: "shared/error", locals: { obj: @dog } %>    

<div class="container">
    <%= form_with(model: @dog, local: true) do |f| %>
      <div class="mb-3">
        <%= f.label :dog_name, "Jméno psa", class: "form-label" %>
        <%= f.text_field :dog_name, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :date_of_birth, "Datum narození", class: "form-label" %>
        <%= f.date_field :date_of_birth, class: "form-control", id: "event_date_picker" %>
      </div>      
      <div class="mb-3">
        <%= f.submit "Upravit", class: "btn btn-warning" %>
      </div>
    <% end %>
    </div>

<div class="container">
    <%= link_to "Zpět na Váš účet", owner_path(current_owner), class: "btn btn-success" %>
</div> 

app/views/dogs/index.html.erb
<div class="container">
<% @dogs.each do |dog| %>
<div class="card text-center" style="width: 30rem;">
    <div class="card-body">
      <h5 class="card-title"><%= dog.dog_name %></h5>
      <p class="card-text"><%= dog.date_of_birth %></p>
      <a href="<%= dog_path(dog) %>" class="btn btn-outline-success">Show details</a>
      <a href="<%= edit_dog_path(dog) %>" class="btn btn-outline-warning">Edit details</a>
      <%= link_to dog_path(dog), method: :delete, class: "btn btn-outline-danger delete-link", data: { turbo_method: :delete, "turbo-confirm": "Are you sure?" } do %>Delete
      <% end %>
    </div>
  </div>
<% end %>
</div>

<div class="container">
    <a href="<%= new_dog_path() %>" class="btn btn-outline-secondary">Add new dog</a>
</div>

app/views/dogs/new.html.erb
<%= render partial: "shared/error", locals: { obj: @dog } %>    



<div class="container">
    <%= form_with(model: @dog, local: true) do |f| %>
      <div class="mb-3">
        <%= f.label :dog_name, class: "form-label" %>
        <%= f.text_field :dog_name, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :date_of_birth, "Datum narození", class: "form-label" %>
        <%= f.date_field :date_of_birth, class: "form-control", id: "event_date_picker" %>
      </div>      
      <div class="field" id="points-field">
      <div class="mb-3">
        <%= f.submit "Uložit",class: "btn btn-warning" %>
      </div>
    <% end %>
    </div>

<div class="container">
    <%= link_to "Zpět na Váš účet", owner_path(current_owner), class: "btn btn-success" %>
</div> 

app/views/dogs/show.html.erb
<% if logged_in? && current_owner.id == @dog.owner_id %>
    <%= render partial: "dog_owner"%>
<% else %>
    <%= render partial: "other_owners"%>
<% end %>